### ISSUE TITLE
New tab "+" icon goes to right side of tab bar

### ISSUE THREAD

**Issue by coltrane58** [yfdyh000/tabutils#154] opened 2017-05-06 13:29 UTC
I just upgraded to Firefox 53.0 and I now have a bit of a problem with the "+" new tab button. It will keep changing position between being immediately after the last tab, which is where it should be, to being all the way over on the right. I can be in one tab and it will be fine. I open another tab and it switches. Argh!
 I am using Tab Utilities Fixed 1.5.2017.02.04. I have reset firefox to the default settings with no extensions and firefox worked fine. I added Tab Utilities and I got the moving "+".

any help would be appreciated
john

**Comment by yfdyh000** [comment] 2017-05-06 13:31
Dupe of #147.

**Closed as completed by yfdyh000** 2017-05-06 13:31 UTC
Labels: bug, duplicate
