### ISSUE TITLE
Broken fullscreen support in Firefox ESR portable 45

### ISSUE THREAD

**Issue by Hubgut** [yfdyh000/tabutils#105] opened 2016-09-16 20:27 UTC
I use Firefox ESR portable and never before had problems with this plug-in.
When I updated to version 45.3.0, I realized that now I can't get the address and tab bars to show when I switched to fullscreen (using [F11]). No matter if I choose to show animations or not, these bars stay hidden when I'm at the top of the screen with my mouse.
If I disable the plug-in, the bars are shown normally.
I also reproduced this problem with a new profile (and no other plug-in installed).

**Comment by yfdyh000** [comment] 2016-09-16 20:29
Duplicate of #51.

**Closed as completed by yfdyh000** 2016-09-16 20:29 UTC
Labels: bug, duplicate

**Comment by Hubgut** [comment] 2016-09-16 20:41
Thanks for your very quick answer. - I did search before, but obviously not with the right phrases. ...
