### ISSUE TITLE
Mouse scroll to focus a tab advances two tabs at a time

### ISSUE THREAD

**Issue by erdemuncuoglu** [yfdyh000/tabutils#112] opened 2016-10-06 16:06 UTC
I'm using FF 51.0a2 (Developer Edition).
- When TUF is disabled mouse whell scrolls the tab bar (if there are too much tabs). Default behavior.
- When mouse scroll is disabled in TUF it can still switch to next tab.
- When mouse scroll is enabled It scrolls two tabs at a time. If I choose invert scroll direction it stops to scroll.
  I made some debugging and it seems like two events fired at the same time. One is from tabutils.js:2353 (the line commented as //Mouse scroll to select) but I couldn't find the other one.

**Comment by erdemuncuoglu** [comment] 2016-10-06 17:04
I found it out. Just an "event.preventDefault();" is enough to fix this. I'm preparing the pull request.

**Comment by yfdyh000** [comment] 2016-12-27 05:58
Dupe of #97.

**Closed as completed by yfdyh000** 2016-12-27 05:58 UTC
Labels: bug, duplicate
