### ISSUE TITLE
Bookmark all tabs feature breaks

### ISSUE THREAD

**Issue by Keith94** [yfdyh000/tabutils#110] opened 2016-09-23 16:50 UTC
Using "Bookmark All Tabs" feature from tab context menu does not seem to save any tabs to bookmarks like it normally would.

**Comment by pruebasaae** [comment] 2016-10-16 03:40
I have this problem. But I´m sure I had this same problem months ago, and i think updating this extension solved it that time. I´ve been searching for it under ISSUES but I have found nothing, perhaps last time was another extension.

**Comment by yfdyh000** [comment] 2016-12-27 06:02
https://github.com/yfdyh000/tabutils/commit/18b2b0941ed0b4ebd8493de7cafa84bf0494db48 fixed this.
Please wait for the review of the 2016.12.27 version.

**Comment by kamizoli** [comment] 2017-01-23 23:00
I updatet to Version 1.5.2016.12.27 two days ago, using Firefox ESR 45.6.0. Since the update the Bookmark all tabs feature is broken. When using it, it will open a small windows without any possibility to name a folder. When the windows is pulled bigger, it is impossible to create a new folder. The hole dialog is broken.

![first open](https://cloud.githubusercontent.com/assets/25310402/22226733/d8bc5d76-e1c7-11e6-825b-651a594b86a3.JPG)
![when pulled bigger](https://cloud.githubusercontent.com/assets/25310402/22226736/e15ac986-e1c7-11e6-8c5f-86c8bcff6bbe.JPG)

With the version before I had no problems.

**Comment by kamizoli** [comment] 2017-01-23 23:08
I went back to version 1.5.2016.07.31. Now it is working again, althought the windows still cuts some of the interface, but it can be pulled bigger to show everything and it is working.

![before](https://cloud.githubusercontent.com/assets/25310402/22226968/03d35dc4-e1c9-11e6-8b64-e4bea84a3b3c.JPG)

**Comment by yfdyh000** [comment] 2017-01-23 23:34
@kamizoli Thank you for your report, I'm sorry to hear the news.
I has checked the TUF 1.5.2016.12.27 with Firefox ESR 45.6.0 and Firefox ESR 45.7.0, but it looks to work well. Maybe you have other add-ons that affect it? Can you reproduce it with another clean profile that contain TUF only. Also, check the Browser Console, maybe it has some clues.

In addition, I also checked it with https://ftp.mozilla.org/pub/firefox/releases/45.6.0esr/win32/de/, the same works for me.

**Comment by kamizoli** [comment] 2017-01-28 22:13
Thank you for your anwser! It took me some time to make some tests. And so far I haven't found the solution. For a while i thought it would be "Edit bookmarks plus" or "Add Bookmark Here²" which causes the problem together with TUF, but in a new profile everything works fine. I will do some more testing, when I find the time.

**Comment by kamizoli** [comment] 2017-02-01 22:45
Dear yfdyh000,
ich have tested some more and am the end of my wits. Using Firefox ESR 45.7.0 with TUF 1.5.2017.01.30 and Add Bookmark Here² 41.0.20160423 (latest for FF 45) it all works fine. Than I install other addons, restarting after every installation and checking "bookmark all tabs" feature every time, it al works. And then suddenly after a restart, sometimes after installing an addon (not always the same addon), sometimes without any changes the dialog window to add bookmark for all tabs is broken. The only thing then is to deaktivate Add Bookmark Here² or to go back to TUF 1.5.2016.07.31 to get it working again. Since ABH² hasn't changed for a long time, I thought it would be TUF causing the problem.

**Comment by yfdyh000** [comment] 2017-02-01 22:57
@kamizoli Thank you for the detailed test. I see this occasional problem with Add Bookmark Here ² 48.0.20160817 and TUF 1.5.2017.01.30 in Fx52b2.

```
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Thu Feb 02 2017 06:52:43 GMT+0800
Full Message: ReferenceError: orgFunc is not defined
Full Stack: @chrome://tabutils/content/tulib.js line 105 > eval:5:25
BookmarkPropertiesPanel.onDialogLoad<@chrome://browser/content/places/bookmarkProperties.js:270:5
TaskImpl_run@resource://gre/modules/Task.jsm:319:42
TaskImpl@resource://gre/modules/Task.jsm:277:3
createAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:252:14
abHere2.hackFunc/obj[name]<@chrome://abhere2/content/editPanelOverlay.js:20:40
TaskImpl_run@resource://gre/modules/Task.jsm:319:42
TaskImpl_handleResultValue@resource://gre/modules/Task.jsm:401:7
TaskImpl_run@resource://gre/modules/Task.jsm:327:15
TaskImpl@resource://gre/modules/Task.jsm:277:3
createAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:252:14
onload@chrome://browser/content/places/bookmarkProperties2.xul:1:1
PUIU_showBookmarkDialog@resource:///modules/PlacesUIUtils.jsm:650:5
abHere2.hackFunc/obj[name]@chrome://abhere2/content/browserOverlay.js:26:34
abHere2.hackFunc/obj[name]@chrome://abhere2/content/browserOverlay.js:26:34
PCH_bookmarkCurrentPages@chrome://tabutils/content/tulib.js line 105 > eval:8:5
oncommand@chrome://browser/content/browser.xul:1:1
  tulib.js%20line%20105%20%3E%20eval:5
```

**Comment by sleek22** [comment] 2017-02-02 02:29
I can confirm a problem that breaks Add Bookmark Here ² dialog to add all bookmarks when you middle click on a folder in Bookmarks Menu. The pop-up to add bookmarks occurs but no listing of number of bookmarks or option to change folder (those areas of the pop-up are blank).

This problem occurs after updating to Tab Utilities Fixed 1.5.2017.01.27 or Tab Utilities Fixed 1.5.2017.01.30. Tab Utilities Fixed 1.5.2016.12.27 did not have this problem.

What's weirder is that uninstalling one of the new versions and rolling back to the version that had no problem does not fix it. It is as if the new version changes some settings that damages it permanently. In my case, I had to reinstall an older saved profile.

Below is the pop-up when working normally on Tab Utilities Fixed 1.5.2016.12.27

![pic](https://cloud.githubusercontent.com/assets/4625685/22534945/dbff5576-e8b4-11e6-87b4-c896788f69d7.png)

Below is after installing Tab Utilities Fixed 1.5.2017.01.30

![pic2](https://cloud.githubusercontent.com/assets/4625685/22535179/8fff11dc-e8b6-11e6-847a-6680d78c509d.png)

**Comment by kamizoli** [comment] 2017-02-02 06:48
That how it looks here as well, when testing. My screenshots above look differnt, because in the beginning i had "Edit bookmarks plus" installed as well. When I tested later without EB+ it looked as sleek22 shows it.
Alltough I'm not sure if I middle clicked on any folder in Bookmark Menu. I will make further tests.
For me gooing back to TUF 1.5.2016.07.31 or disabling Add Bookmark Here ² solves the problem.

In the moment I have Add Bookmark Here ² disabled, because TUF is my most important addon and I need the "Bookmark all tabs" funktion. But without Add Bookmark Here ² adding bookmarks is no joy.
I hope you find a solution.

**Comment by sleek22** [comment] 2017-02-02 08:07
@kamizoli 

"Alltough I'm not sure if I middle clicked on any folder in Bookmark Menu."

This is an option I have enabled in Add Bookmark Here ² so you would have to check if that option is selected on your system. It's the third one over in the setup menu for Add Bookmark Here ² under the "Menu" heading near the bottom.

Also, note in my comment above that the effect was permanent and I had to install an older profile. It changed some setting permanently. I'm current running both Add Bookmark Here ² and the older version of TUF with no problems as I noted above, i.e., version 1.5.2016.12.27

**Comment by yfdyh000** [comment] 2017-02-05 06:20
Fixed in 2017.02.04, please check it.

**Closed as completed by yfdyh000** 2017-02-05 06:20 UTC
Labels: bug, help wanted

**Comment by kamizoli** [comment] 2017-02-07 09:02
It all seems to work again! Thank you!
Off Topic: Will there be a TUF addon after Firefox 57 and the new addon system? Firefox without TUF is just not possible.

**Comment by yfdyh000** [comment] 2017-02-07 17:17
@kamizoli See the https://github.com/yfdyh000/tabutils/issues/130#issuecomment-277509808. Also, I would like to express that I am less likely to develop a new TU(F) from scratch, though I would.

**Comment by sleek22** [comment] 2017-02-07 19:32
I should note that the latest version of TUF solved the Add Bookmark Here ² problem that I wrote about in my comment above.

Thank you to the developer for all your hard work.
