### ISSUE TITLE
TUF breaks Full Screen mode

### ISSUE THREAD

**Issue by LL25255252** [yfdyh000/tabutils#126] opened 2017-01-29 14:20 UTC
In Full Screen mode hovering the top of the screen does nothing. It should display at least the nav-bar.

Tested on a new/fresh Firefox 32bit 51.0.1 profile .
Win 7 x64
TUF  1.5.2017.01.27

**Comment by yfdyh000** [comment] 2017-01-29 14:22
Dupe of #51. Sorry, no progress and research so far.

**Closed as completed by yfdyh000** 2017-01-29 14:22 UTC
Labels: bug, duplicate
