### ISSUE TITLE
3/20/16 Update: New Tabs Can't Load URLs

### ISSUE THREAD

**Issue by seascape** [yfdyh000/tabutils#80] opened 2016-03-21 20:14 UTC
Oof, major problem here, FF45. Since my Tab Utilities Fixed add-on updated to the March 20th version I can no longer open URLs in new tabs, either by mid-clicking a link in an existing tab or creating a new tab and typing a URL. In the former (mid-click) case a blank tab is created and I can't do anything with it but close it.

Items from the main Firefox menu like Options, Add-ons and Customize now do absolutely nothing.

A workaround I found is to enter private browsing mode, then go to about:addons and disable TUFixed. Now everything works normally again albeit without this excellent tabs add-on.

I will try going back to the older version until this resolves. That said, thank you for keeping this essential add-on updated. It is appreciated.

Update: Uh-oh, reverting to 9/2015 version did not resolve, and now the private browsing workaround didn't work. Good thing I still have about:addons open. I'll keep poking around. One thing I did a few weeks ago was enable tab stacking. It has been working fine. Other than that, no obvious new changes outside of add-ons silently updating themselves.

I'm going to revert FF back to last night via CrashPlan backup and quickly disable TU Fixed updates in the 9/2015 version I was running before it updated this morning. I bet that will stabilize it for now. Perhaps something that happens when you update to 3/20/2016 retroactively breaks 9/2015.

Update 2: Reverted to last night with CrashPlan, suppressed TUFixed 03/20/2016 update, so far so good. For some reason about:addons shows Last Updated: December 5, 2015 instead of September, but version is 1.5.2015.09.12.01-let-fixed.

[Dump of TUFixed options](http://pastebin.com/dGx2ABq5)

**Comment by VelvetShadows** [comment] 2016-03-22 00:43
Can't confirm the issue. Updated TUFixed, can still open url's in new tabs as per normal.

**Comment by seascape** [comment] 2016-03-22 02:42
That doesn't surprise me, as if it was obvious the author would've likely caught it before release. There's a fair chance something in TU is interacting badly with some element of my somewhat mature FF profile. The solution here might just be redoing my profile from scratch.

**Comment by VelvetShadows** [comment] 2016-03-22 04:04
Have you tried disabling all other extensions?  See if you can narrow it down as being due to the extension itself or a conflict with another extension.

**Comment by yfdyh000** [comment] 2016-03-22 16:34
The error messages in Browser Console (Ctrl+Shift+J) may be helpful.

I apologize for not guarantee that it is always works fine, since the old architecture, manual testing and technical shortage.

I have encountered another strange problems since Firefox 46 beta, the many features and popup will be broken after some time, although it no longer appears for now.

**Comment by seascape** [comment] 2016-04-04 08:22
I believe this was caused by [Load Tabs Progressively Fixed](https://addons.mozilla.org/en-US/firefox/addon/load-tabs-progressively-fixed/?src=api). Disabling it made tabs and TU Fixed work properly again.

What's odd is that these add-ons coexist for awhile, but then something internal happens and tabs suddenly break. 

Browser console doesn't show any relevant-seeming output, sorry. 

Will continue to monitor.

**Comment by yfdyh000** [comment] 2016-04-04 18:47
Duplicate of #52.

**Closed as completed by yfdyh000** 2016-04-04 18:47 UTC
Labels: bug, duplicate
