### ISSUE TITLE
Open external links in new tab does nothing

### ISSUE THREAD

**Issue by sleek22** [yfdyh000/tabutils#119] opened 2016-12-15 20:49 UTC
When I click on links in external programs, nothing happens. If I change the option in Tab Utilities Fixed to open external links from "New Tab" to "Current Tab", then they do open but always in the same tab, overriding previous content (I have single window mode selected).

I am on pcxFirefox 50.1.0 (64-bit) and Windows 10.

*********UPDATE************

Apparently, I had been testing it from a blank page. When I tested it from any page other than about:blank, it works fine. So it seems to only be a problem when opening external links with the browser on a blank page, i.e., opening external links with "New Tab" setting works as long as you are not on a blank page.

It's now a minor issue.

**Comment by yfdyh000** [comment] 2016-12-24 18:47
Dupe of #103.

**Closed as completed by yfdyh000** 2016-12-24 18:47 UTC
Labels: bug, duplicate
