### ISSUE TITLE
browse buttons are not righ-clicable anymore.

### ISSUE THREAD

**Issue by helppe** [yfdyh000/tabutils#72] opened 2016-01-26 16:53 UTC
hello

about the browse buttons (Buttons number 2 of this picture http://en.flossmanuals.net/firefox/ch013_interface/_booki/firefox/static/Firefox-InterfaceHighlights-ui-en.png found in this page http://en.flossmanuals.net/firefox/ch013_interface/ ) when i right clic on them and select a page in the list, nothing happens at all.
so it is impossible to navigate in the history visited pages anymore with the right clicking method.

if i disable the extension "tab utilities fixed", the issue disappears.

this problem appears since the last versions of firefox.

**Comment by yfdyh000** [comment] 2016-03-20 20:26
Dupe of #68.

**Closed as completed by yfdyh000** 2016-03-20 20:26 UTC
Labels: bug, duplicate
