### ISSUE TITLE
Duplicate External Links

### ISSUE THREAD

**Issue by aaronc8** [yfdyh000/tabutils#143] opened 2017-03-08 21:14 UTC
When I open a link from Thunderbird or Skype, it always opens twice - once in a new tab (as expected) but again in a new window. When I disable tabutils, it doesn't happen. I have tabutils set to open all links in new tab already, too.

I noticed that running tabutils made a new preference of 
"browser.link.open_external"
which seems to disappear when I disable tabutils. Is this an old Firefox preference that is no longer used and now tabutils is bringing it back causing this sort of double-opening of external links?

**Comment by yfdyh000** [comment] 2017-03-08 21:37
Dupe of #101.

**Closed as completed by yfdyh000** 2017-03-08 21:37 UTC
Labels: bug, duplicate
