### ISSUE TITLE
FF v49.0.2 ---> "Mouse scroll to focus a tab" not working...

### ISSUE THREAD

**Issue by wernerml** [yfdyh000/tabutils#114] opened 2016-10-21 03:22 UTC
DAmnnnnnnnnnnnnnnn, this is a Major feature... =(

both other addons who does this,   stopped working too!!!
[Tab Kit](https://addons.mozilla.org/en-US/firefox/addon/tab-kit-mouse-gestures/),   and   [Tab Wheel Scroll
](https://addons.mozilla.org/en-US/firefox/addon/tab-wheel-scroll/)
some major change by FF...

**Comment by yfdyh000** [comment] 2016-12-27 05:57
Dupe of #97.

**Closed as completed by yfdyh000** 2016-12-27 05:57 UTC
Labels: bug, duplicate
